entry: gh-start
executions:
  - src:
      node: gh-start
      port: exec
    dst:
      node: lemon-dog-kiwi
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 300
      y: 380
    inputs: {}
  - id: lemon-dog-kiwi
    type: shell@v1
    position:
      x: 740
      y: 290
    inputs:
      script: env
registries:
  - github:actions/upload-artifact@v3.1.3
description: ''
mtime: 2023-11-30T04:53:55.477Z
