entry: gh-start
executions:
  - src:
      node: kiwi-gray-parrot
      port: exec
    dst:
      node: gray-mango-cherry
      port: exec
  - src:
      node: gray-mango-cherry
      port: exec
    dst:
      node: penguin-dog-blueberry
      port: exec
  - src:
      node: gh-start
      port: exec
    dst:
      node: kiwi-gray-parrot
      port: exec
  - src:
      node: penguin-dog-blueberry
      port: exec
    dst:
      node: blackberry-mango-peach
      port: exec
  - src:
      node: blackberry-mango-peach
      port: exec-win
    dst:
      node: blueberry-lemon-orange
      port: exec
  - src:
      node: blackberry-mango-peach
      port: exec-linux
    dst:
      node: rabbit-dolphin-raspberry
      port: exec
  - src:
      node: blackberry-mango-peach
      port: exec-macos
    dst:
      node: orange-watermelon-lion
      port: exec
connections: []
nodes:
  - id: gh-start
    type: gh-start@v1
    position:
      x: 300
      y: 380
    inputs: {}
  - id: kiwi-gray-parrot
    type: github:actions/checkout
    position:
      x: 580
      y: 390
    inputs: {}
  - id: gray-mango-cherry
    type: github:actions/setup-go
    position:
      x: 1020
      y: 320
    inputs:
      go-version: '>=1.21'
  - id: rabbit-dolphin-raspberry
    type: github:actions/upload-artifact@v3.1.3
    position:
      x: 2040
      y: 110
    inputs:
      name: graph-runner-linux-amd64
      path: graph-runner
  - id: blueberry-lemon-orange
    type: github:actions/upload-artifact@v3.1.3
    position:
      x: 2040
      y: 600
    inputs:
      name: graph-runner-windows-x64
      path: graph-runner.exe
  - id: penguin-dog-blueberry
    type: shell@v1
    position:
      x: 1420
      y: 370
    inputs:
      script: |-
        go mod tidy
        go build .
  - id: orange-watermelon-lion
    type: github:actions/upload-artifact@v3.1.3
    position:
      x: 2040
      y: 360
    inputs:
      name: graph-runner-macos
      path: graph-runner
  - id: blackberry-mango-peach
    type: platform-switch@v1
    position:
      x: 1730
      y: 360
    inputs: {}
registries:
  - github:actions/upload-artifact@v3.1.3
description: ''
mtime: 2023-11-29T18:51:39.258Z
