on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and Publish
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Execute Action Graph
        uses: actionforge/action@v0.4.36-alpha
        with:
          graph_file: build-and-publish.yml
